
version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: tmlmart-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: node:18-alpine
    container_name: tmlmart-backend
    working_dir: /app
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node server.js"

  frontend:
    image: node:18-alpine
    container_name: tmlmart-frontend
    working_dir: /app
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    environment:
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173 --strictPort"

volumes:
  mongo_data: